console.log;
console.log.bind;
console.warn;
console.warn.bind;
console.error;
console.error.bind;
console.group;
console.group.bind;
console.groupEnd;
console.groupEnd.bind;
Object.select;
Object.Fragment;
Object.index;
Object.exec;
Object.getContext;
Object.value;
Object.findDOMNode;
Object.width;
Object.Children;
Object.Children.toArray;
Object.font;
Object.style;
Object.style.position;
Object.style.left;
Object.document;
Object.document.getElementById;
Object.document.open;
Object.document.write;
Object.document.close;
Object.measureText;
Object.render;
Object.setAttribute;
Object.out;
Object.out.println;
Object.createElement;
Object.createElement.apply;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
var clearInterval;
HTMLDocument.prototype.createElement;
HTMLDocument.prototype.execCommand;
HTMLDocument.prototype.getElementById;
var ReactDOM;
goog.DEBUG;
var process;
process.hrtime;
var require;
var setInterval;
var setTimeout;
var createReactClass;
var FlipMove;
document.createElement;
document.title;
var Highlight;
HTMLBodyElement.prototype.appendChild;
HTMLBodyElement.prototype.removeChild;
var React;
var Java;
Java.type;
